% matlab script: WienerHopfAccuracy_Figure3.m
%
% Generates Figure 3 in [1]. The mean results are generated by the script file
% WienerHopfAccuracy_Figure2.m, saved into the file EnsembleMeans.mat.
% Ensemble results for histograms are generated by the file 
% WienerEnsemble_SPLHistSim.m and are saved in the files 
% N{30,300,3000}N20.mat and N{30,300,3000}P10.mat .
%
% [1] Weiss, Proudler, Altmann: "Accuracy of the Wiener-Hopf solution when 
%     based on sample statistics," submitted to IEEE Signal Processing Letter,
%     September 2025. 

% S. Weiss, UoS, 11/9/25 

clear all; close all;

%--------------------------------------------------------------------
% parameters
%--------------------------------------------------------------------
M = 5; Ns = [30 300 3000]';
SNR2 =  [-10 30];
wopt = [0.0602 + 0.1972i;
  -0.0365 - 0.3547i;
   0.4376 + 0.2107i;
   0.4139 + 0.4789i;
   0.4163 + 0.1436i];
A = [ 0.0722 - 0.2938i   0.1469 - 0.1875i  -0.0904 + 0.1025i   0.0332 + 0.0682i   0.1842 - 0.1123i;
  -0.0375 + 0.0757i  -0.1013 - 0.0262i   0.0401 - 0.1111i   0.0498 + 0.0481i  -0.0309 + 0.2126i;
  -0.3187 - 0.0574i  -0.2856 - 0.1483i  -0.0347 + 0.0693i   0.0590 - 0.0027i  -0.1501 - 0.0246i;
   0.1256 - 0.1964i   0.2101 - 0.3097i  -0.1436 + 0.1867i  -0.1105 - 0.0320i   0.0459 - 0.0842i;
   0.2223 + 0.2049i   0.0916 - 0.0409i  -0.2811 - 0.0373i  -0.0666 + 0.0172i   0.5419 + 0.1905i];  
R = A*A';

%--------------------------------------------------------------------
% theoretical values
%--------------------------------------------------------------------

% noise-related error term
xi_v1 = (1./(Ns-M))*10.^(-SNR2/10)*trace(inv(R));
xi_v2 = (1./Ns)*10.^(-SNR2/10)*trace(inv(R));
xi_v3 = (Ns.^2)./(Ns-M).^3*10.^(-SNR2/10)*trace(inv(R));

% system-related error term
xi_w2 = (1./Ns)*ones(size(SNR2))*trace(inv(R))*trace(R*wopt*wopt');
xi_w3 = (Ns+M.^2*Ns - M.^3 + M)./( (Ns-M).*( (Ns-M).^2-1 ) )*trace(wopt*wopt') + ...
         2*Ns.^2./( (Ns-M).*( (Ns-M).^2-1 ) ) *trace(inv(R))*  trace(R*wopt*wopt') ;
xi_w1 = zeros(size(xi_w2));

% overall system error
xi_1 = 10*log10(xi_v1 + xi_w1); 
xi_2 = 10*log10(xi_v2 + xi_w2); 
xi_3 = 10*log10(xi_v3 + xi_w3);

% load ensemble means
load EnsembleMeans.mat
EMeans = 10*log10(EnsembleMeans);
E = [0 0.4];

%-----------------------------------------------------------------
%   extract and plot results for -10dB SNR
%-----------------------------------------------------------------
%subplot(211);
clf;
B = 0.1;
load N3e1M10.mat
xx1 = x1(1:end-1)+diff(x1);
plot(10*log10(xx1(1:end-1)),y1(1:end-1)/max(y1(1:end-1)),'b--');
hold on;
plot(10*log10(xx1),y2/max(y2),'b-');
plot(10*log10(xx1),y3/max(y3),'b-.');
plot(xi_3(1,1),B,'bs');
plot(xi_2(1,1),B,'b*');
plot(xi_1(1,1),B,'bo');
% N = 300;
load N3e2M10.mat
xx1 = x1(1:end-1)+diff(x1);
xx2 = x2(1:end-1)+diff(x2);
xx3 = x3(1:end-1)+diff(x3);
plot(10*log10(xx1),y1/max(y1),'r--');
hold on;
plot(10*log10(xx2),y2/max(y2),'r-');
plot(10*log10(xx3),y3/max(y3),'r-.');
plot(xi_3(2,1),B,'rs');
plot(xi_2(2,1),B,'r*');
plot(xi_1(2,1),B,'ro');
% N = 3000;
load N3e3M10.mat
xx1 = x1(1:end-1)+diff(x1);
xx2 = x2(1:end-1)+diff(x2);
xx3 = x3(1:end-1)+diff(x3);
plot(10*log10(xx1),y1/max(y1),'--','color',[0 0.5 0]);
hold on;
plot(10*log10(xx2),y2/max(y2),'-','color',[0 0.5 0]);
plot(10*log10(xx3),y3/max(y3),'-.','color',[0 0.5 0]);
plot(xi_3(3,1),B,'s','color',[0 0.5 0]);
plot(xi_2(3,1),B,'*','color',[0 0.5 0]);
plot(xi_1(3,1),B,'o','color',[0 0.5 0]);
grid on;
axis([-50 40 0 1]);
%
plot([1 1]*EMeans(1,1),E,'b--');
plot([1 1]*EMeans(2,1),E,'r--');
plot([1 1]*EMeans(3,1),E,'--','color',[0 0.5 0]);
%
plot([1 1]*EMeans(4,1),E,'b-');
plot([1 1]*EMeans(5,1),E,'r-');
plot([1 1]*EMeans(6,1),E,'-','color',[0 0.5 0]);
%
plot([1 1]*EMeans(7,1),E,'b-.');
plot([1 1]*EMeans(8,1),E,'r-.');
plot([1 1]*EMeans(9,1),E,'-.','color',[0 0.5 0]);
%
text(-48,0.75,'(a) SNR=-10~dB','interpreter','latex');
ylabel('$\frac{\hat{p}( \| \mbox{\boldmath $\epsilon$} \|_2^2 ) }{ \max\{\hat{p}(\|\mbox{\boldmath $\epsilon$} \|_2^2)\}}$','interpreter','latex');
%ylabel('$\hat{p}( \| \mbox{\boldmath $\epsilon$} \|_2^2 )/ \max\{\hat{p}(\|\mbox{\boldmath $\epsilon$} \|_2^2)\}$','interpreter','latex');

set(gcf,'OuterPosition',[230 250 570 170]);
set(gca,'LooseInset',get(gca,'TightInset'));  
print -depsc SPL25_2_Fig3a.eps


%-----------------------------------------------------------------
%   SNR 30dB
%-----------------------------------------------------------------
%subplot(212);
clf;
% N = 30
load N3e1P30.mat
xx1 = x1(1:end-1)+diff(x1);
xx2 = x2(1:end-1)+diff(x2);
xx3 = x3(1:end-1)+diff(x3);
plot(10*log10(xx1),y1/max(y1),'b--');
hold on;
plot(10*log10(xx2),y2/max(y2),'b-');
plot(10*log10(xx3),y3/max(y3),'b-.');
plot(xi_3(1,2),B,'bs');
plot(xi_2(1,2),B,'b*');
plot(xi_1(1,2),B,'bo');
grid on;
axis([-50 40 0 1]);
% N = 300;
load N3e2P30.mat
xx1 = x1(1:end-1)+diff(x1);
xx2 = x2(1:end-1)+diff(x2);
xx3 = x3(1:end-1)+diff(x3);
plot(10*log10(xx1),y1/max(y1),'r--');
hold on;
plot(10*log10(xx2),y2/max(y2),'r-');
plot(10*log10(xx3),y3/max(y3),'r-.');
plot(xi_3(2,2),B,'rs');
plot(xi_2(2,2),B,'r*');
plot(xi_1(2,2),B,'ro');
% N = 3000;
load N3e3P30.mat
xx1 = x1(1:end-1)+diff(x1);
xx2 = x2(1:end-1)+diff(x2);
xx3 = x3(1:end-1)+diff(x3);
plot(10*log10(xx1),y1/max(y1),'--','color',[0 0.5 0]);
hold on;
plot(10*log10(xx2),y2/max(y2),'-','color',[0 0.5 0]);
plot(10*log10(xx3),y3/max(y3),'-.','color',[0 0.5 0]);
plot(xi_3(3,2),B,'s','color',[0 0.5 0]);
plot(xi_2(3,2),B,'*','color',[0 0.5 0]);
plot(xi_1(3,2),B,'o','color',[0 0.5 0]);
%
plot([1 1]*EMeans(1,2),E,'b--');
plot([1 1]*EMeans(2,2),E,'r--');
plot([1 1]*EMeans(3,2),E,'--','color',[0 0.5 0]);
%
plot([1 1]*EMeans(4,2),E,'b-');
plot([1 1]*EMeans(5,2),E,'r-');
plot([1 1]*EMeans(6,2),E,'-','color',[0 0.5 0]);
%
plot([1 1]*EMeans(7,2),E,'b-.');
plot([1 1]*EMeans(8,2),E,'r-.');
plot([1 1]*EMeans(9,2),E,'-.','color',[0 0.5 0]);
%
text(20,0.75,'(b) SNR=30~dB','interpreter','latex');
%xlabel('$\hat{p}( \| \mbox{\boldmath $\epsilon$} \|_2^2 )/ \max\{\hat{p}(\|\mbox{\boldmath $\epsilon$} \|_2^2)\}$','interpreter','latex');
ylabel('$\frac{\hat{p}( \| \mbox{\boldmath $\epsilon$} \|_2^2 ) }{ \max\{\hat{p}(\|\mbox{\boldmath $\epsilon$} \|_2^2)\}}$','interpreter','latex');
xlabel('$\|\mbox{\boldmath $\mathbf{\epsilon}$}||_2^2$ / [dB]','interpreter','latex');

set(gcf,'OuterPosition',[230 250 570 190]);
set(gca,'LooseInset',get(gca,'TightInset'));  
print -depsc SPL25_2_Fig3b.eps

